logging:
  level:
    org:
      unidue:
        ub:
          libintel:
            almaconnector:
              client: debug
              repository: debug
              service: debug
              controller: debug