logging:
  level:
    org:
      unidue:
        ub:
          libintel:
            almaconnector:
              repository:
                elasticsearch: debug
              service: debug
              controller: debug
