feign:
  httpclient:
    disableSslValidation: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      items:
        connectTimeout: 600000
        readTimeout: 600000
      invoices:
        connectTimeout: 600000
        readTimeout: 600000
      jobs:
        connectTimeout: 600000
        readTimeout: 600000
server:
  port: ${server_port:11889}
spring:
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
